# Generated by Django 5.1.1 on 2024-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0002_alter_car_co2_배출_alter_car_가격_alter_car_계기판_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='시트배열',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
