# Generated by Django 5.1.1 on 2024-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0003_alter_car_시트배열'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='운전석',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='트림명',
            field=models.TextField(blank=True, null=True),
        ),
    ]
