# Generated by Django 5.1.1 on 2024-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0004_alter_car_운전석_alter_car_트림명'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='보조금_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
