# Generated by Django 5.1.1 on 2024-09-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0006_alter_users_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
