# Generated by Django 5.1.1 on 2024-09-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0007_remove_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='def', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
