# Generated by Django 5.1.1 on 2024-09-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0008_users_is_active_users_is_staff_users_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userpw',
        ),
    ]
