# Generated by Django 5.1.1 on 2024-10-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0011_users_delete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='사진',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
