# Generated by Django 5.1.1 on 2024-10-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0013_oil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('도', models.CharField(max_length=50)),
                ('시', models.CharField(max_length=50)),
                ('차종', models.CharField(max_length=50)),
                ('제조사', models.CharField(max_length=50)),
                ('모델명', models.CharField(max_length=100)),
                ('국가보조금', models.DecimalField(decimal_places=1, max_digits=5)),
                ('지자체보조금', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'db_table': 'subsidy',
                'managed': False,
            },
        ),
    ]
