# Generated by Django 5.1.1 on 2024-10-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0014_subsidy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('차종', models.CharField(max_length=50)),
                ('제조사', models.CharField(max_length=50)),
                ('모델명', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ev_car',
                'managed': False,
            },
        ),
    ]
