# Generated by Django 5.1.1 on 2024-10-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0016_usedcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('도로명주소', models.CharField(max_length=255)),
                ('전체대수', models.IntegerField()),
                ('전기차대수', models.IntegerField()),
                ('충전기대수_지상', models.IntegerField()),
                ('충전기대수_지하', models.IntegerField()),
            ],
            options={
                'db_table': 'apt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AptCharger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apt_id', models.IntegerField()),
                ('규격', models.CharField(max_length=255)),
                ('충전속도', models.CharField(max_length=50)),
                ('개수', models.IntegerField(blank=True, null=True)),
                ('사업자', models.CharField(max_length=255)),
                ('회원가', models.DecimalField(decimal_places=1, max_digits=10)),
                ('비회원가', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'db_table': 'apt_charger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('주소', models.CharField(blank=True, max_length=255, null=True)),
                ('충전소명', models.CharField(blank=True, max_length=255, null=True)),
                ('충전량', models.CharField(blank=True, max_length=100, null=True)),
                ('운영기관', models.CharField(blank=True, max_length=255, null=True)),
                ('충전기타입', models.CharField(blank=True, max_length=100, null=True)),
                ('이용자제한', models.CharField(blank=True, max_length=100, null=True)),
                ('회원가', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('비회원가', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('위도', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('경도', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'charger',
                'managed': False,
            },
        ),
    ]
